### ISSUE TITLE
数据库密码加密有bug

### ISSUE THREAD

**Issue by luoyan01123** [iBase4J/iBase4J#90]
数据库密码加密部分有bug，部分加密出来的密码不能使用

**Comment by futurezhangkai** [comment]
Exception in thread "main" java.lang.RuntimeException: 解密错误，错误信息：
	at org.ibase4j.SecurityUtil.decryptDes(SecurityUtil.java:77)
	at org.ibase4j.SecurityUtil.decryptDes(SecurityUtil.java:40)
	at org.ibase4j.SecurityUtil.main(SecurityUtil.java:153)

不能解密

**Comment by ludan369** [comment]
关于数据库加密问题。看了下ibase4j-common的commit记录
其中加密解密为：byte = [57, 48, 49, 51, 57, 49, 49, 57]，是"90139119"这个字符串getByte()得到的。
可以这样加解密：
byte[] key = {57,48,49,51,57,49,49,57};
System.out.println(SecurityUtil.encryptDes("你的数据库密码",key));
